version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1492
      - PGID=1492
      - TZ=Etc/GB
      - WEBUI_PORT=8781
    volumes:
      - /var/media/qbittorrent/appdata/config:/config
      - /var/media/qbittorrent/downloads:/downloads
    ports:
      - 8781:8781
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1492
      - PGID=1492
      - TZ=Etc/GB
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /var/media/jackett/data:/config
      - /var/media/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1492
      - PGID=1492
      - TZ=Etc/GB
    volumes:
      - /var/media/sonarr/data:/config
      - /var/media/series:/tv #optional
      - /var/media/qbittorrent/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1492
      - PGID=1492
      - TZ=Etc/GB
    volumes:
      - /var/media/radarr/data:/config
      - /var/media/movies:/movies #optional
      - /var/media/qbittorrent/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1492
      - PGID=1492
      - TZ=Etc/GB
      - JELLYFIN_PublishedServerUrl=192.168.1.3 #optional
    volumes:
      - /var/media/data:/config
      - /var/media/series:/data/tvshows
      - /var/media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
